export type MarketStatus = 'active' | 'expansion' | 'future'

export type Market = {
  slug: string
  name: string
  region: string
  state?: string
  status: MarketStatus
  statusLabel: string
  blurb: string
  services: string[]
  /** Geographic coordinates used for the map projection. */
  coords: { lat: number; lon: number }
}

/** Live zones from the Urban Goodz platform API (zone/list, all status: 1). */
export const markets: Market[] = [
  {
    slug: 'houston',
    name: 'Houston',
    state: 'TX',
    region: 'Greater Houston Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb:
      'Our launch market and home base. Built here in 2020, Houston is where the platform, the mission and the community first came together — and it stays the heartbeat of the network.',
    services: [
      'Marketplace & local shopping',
      'Restaurants & groceries',
      'Order Anywhere',
      'Book Services',
      'Fashion Fit',
      'Medical Courier',
      'Freight & load board',
      'Business Portal',
      'Driver Platform',
      'AI',
    ],
    coords: { lat: 29.76, lon: -95.37 },
  },
  {
    slug: 'dallas',
    name: 'Dallas',
    state: 'TX',
    region: 'Greater Dallas Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'A major Texas commerce hub and the anchor of the North Texas corridor.',
    services: ['Marketplace', 'Restaurants', 'Order Anywhere', 'Business Portal', 'Driver Platform'],
    coords: { lat: 32.78, lon: -96.8 },
  },
  {
    slug: 'austin',
    name: 'Austin',
    state: 'TX',
    region: 'Greater Austin Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'The capital city — a fast-growing market for local commerce and services.',
    services: ['Marketplace', 'Restaurants', 'Book Services', 'Fashion Fit', 'Driver Platform'],
    coords: { lat: 30.27, lon: -97.74 },
  },
  {
    slug: 'gulf-coast',
    name: 'Gulf Coast Texas',
    state: 'TX',
    region: 'Brazoria · Matagorda · Galveston · Wharton',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'Coastal Texas communities — Galveston to Matagorda — served as one corridor.',
    services: ['Marketplace', 'Restaurants', 'Groceries', 'Freight', 'Driver Platform'],
    coords: { lat: 29.05, lon: -95.6 },
  },
  {
    slug: 'huntsville',
    name: 'Huntsville',
    state: 'AL',
    region: 'Greater Huntsville Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'A rocket city — and one of the first Alabama markets live on the platform.',
    services: ['Marketplace', 'Restaurants', 'Book Services', 'Driver Platform'],
    coords: { lat: 34.73, lon: -86.59 },
  },
  {
    slug: 'birmingham',
    name: 'Birmingham',
    state: 'AL',
    region: 'Greater Birmingham Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'Alabama’s largest metro, live with local commerce and delivery.',
    services: ['Marketplace', 'Restaurants', 'Groceries', 'Driver Platform'],
    coords: { lat: 33.52, lon: -86.8 },
  },
  {
    slug: 'atlanta',
    name: 'Atlanta',
    state: 'GA',
    region: 'Greater Atlanta Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'A national hub for Black entrepreneurship and commerce — live in the Southeast.',
    services: ['Marketplace', 'Restaurants', 'Creator Commerce', 'Events', 'Driver Platform'],
    coords: { lat: 33.75, lon: -84.39 },
  },
  {
    slug: 'memphis',
    name: 'Memphis',
    state: 'TN',
    region: 'Memphis Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'The home of soul and logistics — live with local commerce and freight.',
    services: ['Marketplace', 'Restaurants', 'Freight', 'Driver Platform'],
    coords: { lat: 35.15, lon: -90.05 },
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    state: 'CA',
    region: 'Greater Los Angeles Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'The largest West Coast market, live across the LA basin.',
    services: ['Marketplace', 'Restaurants', 'Creator Commerce', 'Fashion Fit', 'Freight'],
    coords: { lat: 34.05, lon: -118.24 },
  },
  {
    slug: 'las-vegas',
    name: 'Las Vegas',
    state: 'NV',
    region: 'Greater Las Vegas Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'A 24/7 city built for on-demand — live in the desert Southwest.',
    services: ['Marketplace', 'Restaurants', 'Events', 'Book Services', 'Driver Platform'],
    coords: { lat: 36.17, lon: -115.14 },
  },
  {
    slug: 'miami',
    name: 'Miami',
    state: 'FL',
    region: 'Greater Miami Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'Gateway to the Caribbean — a strategic international bridge market.',
    services: ['Marketplace', 'Restaurants', 'Freight', 'Events', 'Driver Platform'],
    coords: { lat: 25.76, lon: -80.19 },
  },
  {
    slug: 'dmv',
    name: 'Washington DC',
    state: 'DC',
    region: 'Greater DMV Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'The nation’s capital and its Maryland–Virginia suburbs, live as one DMV market.',
    services: ['Marketplace', 'Restaurants', 'Book Services', 'Business Portal', 'Driver Platform'],
    coords: { lat: 38.9, lon: -77.04 },
  },
  {
    slug: 'tulsa',
    name: 'Tulsa',
    state: 'OK',
    region: 'Greater Tulsa Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'A rising hub for Black entrepreneurship — live in the heartland.',
    services: ['Marketplace', 'Restaurants', 'Book Services', 'Driver Platform'],
    coords: { lat: 36.15, lon: -95.99 },
  },
  {
    slug: 'charlotte',
    name: 'Charlotte',
    state: 'NC',
    region: 'Greater Charlotte Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'A growing financial and logistics center, live in the Southeast.',
    services: ['Marketplace', 'Restaurants', 'Freight', 'Business Portal', 'Driver Platform'],
    coords: { lat: 35.23, lon: -80.84 },
  },
  {
    slug: 'new-york-city',
    name: 'New York City',
    state: 'NY',
    region: 'Greater NYC Area',
    status: 'active',
    statusLabel: 'Live market',
    blurb: 'The largest U.S. market — live as the anchor of the East Coast.',
    services: ['Marketplace', 'Restaurants', 'Book Services', 'Fashion Fit', 'Freight'],
    coords: { lat: 40.71, lon: -74.01 },
  },
]

/** Next cities on the rollout roadmap — not yet live, planned expansion. */
export const expansionMarkets: Market[] = [
  {
    slug: 'san-antonio',
    name: 'San Antonio',
    state: 'TX',
    region: 'Texas',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'One of the largest cities in the U.S. on our Texas corridor.',
    services: ['Marketplace', 'Restaurants', 'Driver Platform'],
    coords: { lat: 29.42, lon: -98.49 },
  },
  {
    slug: 'fort-worth',
    name: 'Fort Worth',
    state: 'TX',
    region: 'Texas',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'Part of the Dallas–Fort Worth metro rollout.',
    services: ['Marketplace', 'Restaurants', 'Driver Platform'],
    coords: { lat: 32.76, lon: -97.33 },
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    state: 'IL',
    region: 'Midwest',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'The largest Midwest market on our expansion roadmap.',
    services: ['Marketplace', 'Restaurants', 'Freight', 'Business Portal'],
    coords: { lat: 41.88, lon: -87.63 },
  },
  {
    slug: 'new-orleans',
    name: 'New Orleans',
    state: 'LA',
    region: 'Southeast',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'A Gulf Coast culture and commerce anchor next on the map.',
    services: ['Marketplace', 'Restaurants', 'Events'],
    coords: { lat: 29.95, lon: -90.07 },
  },
  {
    slug: 'nashville',
    name: 'Nashville',
    state: 'TN',
    region: 'Southeast',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'A fast-growing Southern music and business capital.',
    services: ['Marketplace', 'Restaurants', 'Events', 'Driver Platform'],
    coords: { lat: 36.16, lon: -86.78 },
  },
  {
    slug: 'detroit',
    name: 'Detroit',
    state: 'MI',
    region: 'Midwest',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'A historic hub of Black entrepreneurship and industry.',
    services: ['Marketplace', 'Restaurants', 'Freight'],
    coords: { lat: 42.33, lon: -83.05 },
  },
  {
    slug: 'philadelphia',
    name: 'Philadelphia',
    state: 'PA',
    region: 'Northeast',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'A major Northeast metro on the East Coast corridor.',
    services: ['Marketplace', 'Restaurants', 'Driver Platform'],
    coords: { lat: 39.95, lon: -75.17 },
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    state: 'AZ',
    region: 'Southwest',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'One of the fastest-growing metros in the Southwest.',
    services: ['Marketplace', 'Restaurants', 'Driver Platform'],
    coords: { lat: 33.45, lon: -112.07 },
  },
  {
    slug: 'denver',
    name: 'Denver',
    state: 'CO',
    region: 'Mountain West',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'The anchor of the Mountain West rollout.',
    services: ['Marketplace', 'Restaurants', 'Book Services'],
    coords: { lat: 39.74, lon: -104.99 },
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    state: 'WA',
    region: 'Pacific Northwest',
    status: 'expansion',
    statusLabel: 'Planned expansion',
    blurb: 'The Pacific Northwest gateway on the West Coast roadmap.',
    services: ['Marketplace', 'Restaurants', 'Creator Commerce'],
    coords: { lat: 47.61, lon: -122.33 },
  },
]

export const futureVision = [
  { region: 'Canada', note: 'North American expansion beyond the U.S.' },
  { region: 'Mexico', note: 'Cross-border commerce and logistics' },
  { region: 'Caribbean', note: 'Connecting island communities and diaspora commerce' },
  { region: 'Africa', note: 'Long-term global vision and diaspora bridges' },
  { region: 'Europe', note: 'Long-term international expansion' },
  { region: 'South America', note: 'Long-term international expansion' },
  { region: 'Middle East', note: 'Long-term international expansion' },
]

export const activeMarkets = markets.filter((m) => m.status === 'active')

export const getMarket = (slug: string) => markets.find((m) => m.slug === slug)
