/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PressRouteImport } from './routes/press'
import { Route as PreviewPhonesRouteImport } from './routes/preview-phones'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPhonesRoute = PreviewPhonesRouteImport.update({
  id: '/preview-phones',
  path: '/preview-phones',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/markets': typeof MarketsRoute
  '/platform': typeof PlatformRoute
  '/press': typeof PressRoute
  '/preview-phones': typeof PreviewPhonesRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/markets': typeof MarketsRoute
  '/platform': typeof PlatformRoute
  '/press': typeof PressRoute
  '/preview-phones': typeof PreviewPhonesRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/markets': typeof MarketsRoute
  '/platform': typeof PlatformRoute
  '/press': typeof PressRoute
  '/preview-phones': typeof PreviewPhonesRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/coming-soon'
    | '/contact'
    | '/join'
    | '/markets'
    | '/platform'
    | '/press'
    | '/preview-phones'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/coming-soon'
    | '/contact'
    | '/join'
    | '/markets'
    | '/platform'
    | '/press'
    | '/preview-phones'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai'
    | '/coming-soon'
    | '/contact'
    | '/join'
    | '/markets'
    | '/platform'
    | '/press'
    | '/preview-phones'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  JoinRoute: typeof JoinRoute
  MarketsRoute: typeof MarketsRoute
  PlatformRoute: typeof PlatformRoute
  PressRoute: typeof PressRoute
  PreviewPhonesRoute: typeof PreviewPhonesRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-phones': {
      id: '/preview-phones'
      path: '/preview-phones'
      fullPath: '/preview-phones'
      preLoaderRoute: typeof PreviewPhonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  JoinRoute: JoinRoute,
  MarketsRoute: MarketsRoute,
  PlatformRoute: PlatformRoute,
  PressRoute: PressRoute,
  PreviewPhonesRoute: PreviewPhonesRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
